# trabajamos con javascript
language: node_js
# os: osx
# hay mas configuraciones
git:
  # 3 niveles de git
  depth: 3

branches:
  # branches que no queremos implementar
  except:
  - legacy
  - experimental

branches:
  # solo las ramas que queremos
  only:
  - master
  - stable

before_install: #antes de hacerlo
  - python

install:
  - npm install
# - yarn install
# - apt install curl

script:
  - npm deploy
  - npm test
  # - yarn deploy
  # - yarn test

before_script:
  - clean

after_script:
  - npm clean
  # - yarn clean

cache:
  directories:
    - node_modules # mantener en cache node_modules

jobs:
  include:
    - stage: test
      script: npm test
      script: npm eslint
      # script: yarn test
      # script: yarn eslint
    - stage: deploy
      script: npm deploy
      # script: yarn deploy

# deploy github page y heroku

deploy:
  provider: heroku
  on
    repo: Diego-Luna/platzistore